# Generated by Django 4.1.13 on 2024-03-13 21:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryPlanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('preferences', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gemini_vision/')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('raw_response', models.JSONField(default=list)),
                ('places_details', models.JSONField(default=list)),
            ],
        ),
    ]
