# Generated by Django 4.2.5 on 2023-09-10 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tour_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('contact_number', models.CharField(max_length=12)),
                ('address', models.TextField()),
                ('special_requests', models.TextField()),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Traveller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('age', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('destinations', models.JSONField(default=list)),
                ('duration', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(default=0)),
                ('itinerary', models.JSONField(default=list)),
                ('category', models.CharField(choices=[('North India', 'North India'), ('South India', 'South India'), ('West India', 'West India'), ('East India', 'East India'), ('Foreign', 'Foreign'), ('Trekking', 'Trekking'), ('Rafting', 'Rafting'), ('Wildlife', 'Wildlife'), ('Heritage', 'Heritage'), ('Pilgrimage', 'Pilgrimage')], max_length=40)),
                ('images', models.ManyToManyField(to='tour.image')),
                ('orders', models.ManyToManyField(to='tour.order')),
                ('slots', models.ManyToManyField(to='tour.slot')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='travellers',
            field=models.ManyToManyField(to='tour.traveller'),
        ),
    ]
