# Generated by Django 4.2.5 on 2023-09-10 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_order_state_alter_order_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
    ]
