# Generated by Django 4.2.5 on 2023-10-06 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('tour', '0003_remove_order_country_remove_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.tour'),
        ),
        migrations.AddField(
            model_name='slot',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.tour'),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_type',
            field=models.CharField(choices=[('bestsellers', 'Our Bestsellers'), ('foreign', 'Foreign'), ('monsoon_musts', 'Monsoon Musts'), ('winter_wonders', 'Winter Wonders'), ('summer_specials', 'Summer Specials'), ('pilgrimage', 'Pilgrimage'), ('trekking', 'Trekking'), ('camping', 'Camping'), ('safari', 'Safari'), ('agro_tourism', 'Agro Tourism'), ('rafting', 'Rafting'), ('carnival', 'Carnival')], default='bestsellers', max_length=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.ForeignKey(blank=True, limit_choices_to={'country__name': 'India'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.subregion'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='images',
            field=models.ManyToManyField(related_name='images_for_tour', to='tour.image'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='slots',
            field=models.ManyToManyField(related_name='slots_for_tour', to='tour.slot'),
        ),
    ]
