# Generated by Django 4.2.5 on 2023-10-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_image_tour_slot_tour_tour_tour_type_alter_order_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='images',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='slots',
        ),
        migrations.AlterField(
            model_name='tour',
            name='category',
            field=models.CharField(choices=[('North_India', 'North India'), ('South_India', 'South India'), ('West_India', 'West India'), ('East_India', 'East India'), ('Foreign', 'Foreign'), ('Trekking', 'Trekking'), ('Rafting', 'Rafting'), ('Wildlife', 'Wildlife'), ('Heritage', 'Heritage'), ('Pilgrimage', 'Pilgrimage')], max_length=40),
        ),
    ]
