# Generated by Django 4.2.5 on 2023-10-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_remove_tour_images_remove_tour_slots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='review',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
