# Generated by Django 4.2.5 on 2023-10-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_order_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='duration',
        ),
        migrations.AddField(
            model_name='tour',
            name='days',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='tour',
            name='nights',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
