# Generated by Django 4.2.5 on 2023-10-08 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0007_remove_tour_duration_tour_days_tour_nights'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
                ('tour_description', models.TextField()),
                ('departure_date', models.DateField()),
                ('number_of_days', models.PositiveIntegerField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour')),
            ],
        ),
    ]
