# Generated by Django 4.2.5 on 2023-10-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_tourinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
