# Generated by Django 4.2.5 on 2023-10-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0009_order_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='itinerary',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
