# Generated by Django 4.2.2 on 2023-10-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0010_alter_tour_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='is_bestsellers',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tour',
            name='category',
            field=models.CharField(choices=[('North_India', 'North India'), ('South_India', 'South India'), ('West_India', 'West India'), ('East_India', 'East India'), ('Foreign', 'Foreign')], max_length=40),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_type',
            field=models.CharField(choices=[('foreign', 'Foreign'), ('monsoon_musts', 'Monsoon Musts'), ('winter_wonders', 'Winter Wonders'), ('summer_specials', 'Summer Specials'), ('pilgrimage', 'Pilgrimage'), ('trekking', 'Trekking'), ('camping', 'Camping'), ('safari', 'Safari'), ('agro_tourism', 'Agro Tourism'), ('rafting', 'Rafting'), ('carnival', 'Carnival')], default='camping', max_length=60),
        ),
    ]
